apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devflowfix

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/name: devflowfix
  app.kubernetes.io/component: frontend
  app.kubernetes.io/managed-by: kustomize

images:
  - name: parthsinha90/devflowfix
    newTag: v1.0
